### ISSUE TITLE
Private plugins not supported

### ISSUE THREAD

**Issue by jeroenvandijk** [technomancy/s3-wagon-private#14]
We have deployed a private plugin to an S3 repo via this library. However, when the plugin has not been fetched before (e.g. via normal :dependencies) just declaring our private plugin dependency will not make Leiningen find it.

Any suggestions where to fix this?

**Comment by danielcompton** [comment]
Not sure if there is a good solution to this, as technomancy has said, it's a tricky bootstrapping issue. If it works putting it in `:dev`, then that's a good workaround.
