### ISSUE TITLE
403 errors with S3-wagon-private

### ISSUE THREAD

**Issue by marick** [technomancy/s3-wagon-private#19]
For our local repo, we want to deploy as follows:

```clojure
 :repositories [["private" {:url "s3p://REPONAME/releases/"
                            :username :env
                            :passphrase :env
                            :sign-releases false}]]
```

`lein deploy private` produces the following:

```
Sending getset/getset/1.1.0/getset-1.1.0.pom 
   to s3p://REPONAME/releases/
Nov 14, 2014 5:32:29 PM org.jets3t.service.impl.rest.httpclient.RestS3Service performRequest
WARNING: Error Response: PUT '/releases%2Fgetset%2Fgetset%2F1.1.0%2F' -- ResponseCode: 403, ResponseStatus: Forbidden, …
SEVERE: Request Failed.
```

This doesn’t seem to be https://github.com/technomancy/leiningen/issues/843 - I may have had the wrong passphrase the first time, but I’ve waited over 48 hours and the same thing happens again.

I’m curious why the PUT is urlencoded.

```
Leiningen 2.5.0 on Java 1.7.0_21 Java HotSpot(TM) 64-Bit Server VM
 :plugins [[s3-wagon-private "1.1.2"]]
```

**Comment by huahaiy** [comment]
This is fixed in fork: https://clojars.org/circle/s3-wagon-private

**Comment by danielcompton** [comment]
The circle fork was merged back into master, so this should be fixed now.
