### ISSUE TITLE
Error 404 question

### ISSUE THREAD

**Issue by gmeroz** [technomancy/s3-wagon-private#23]
Hi,
I'm running the same project on Linux machines and on Mac OX. On the Linux machines it's working well but on the Mac it fails to load the private repository.

The username & passphrase are the same. Actually the project files are the same as I only checked them out from the source control.

Retrieving coralogix/coralogix.sdk/1.0.0/coralogix.sdk-1.0.0.pom from private
Jul 02, 2015 12:33:49 PM org.jets3t.service.impl.rest.httpclient.RestS3Service performRequest
WARNING: Error Response: GET '/releases%2Fcoralogix%2Fcoralogix.sdk%2F1.0.0%2Fcoralogix.sdk-1.0.0.pom.sha1' -- ResponseCode: 404, ResponseStatus: Not Found, Request Headers: [Content-Type: , Date: Thu, 02 Jul 2015 09:33:49 GMT, Authorization: AWS AKIxxxxxxxxxxxxxx:7oXh+WxxxxxxxxxxxxQ=, User-Agent: JetS3t/0.7.1 (Mac OS X/10.10.1; x86_64; en; JVM 1.8.0_11), Host: clojure-deps.s3.amazonaws.com], Response Headers: [x-amz-request-id: 5FC7E6FD1A73BFF6, x-amz-id-2: hPYbS6IicikvZ+wiZP4MzveZxqLQOZMAfTg5htULtYm/C1TqHRGr/1iirwN3ZM0Ypb9BHPplE/4=, Content-Type: application/xml, Transfer-Encoding: chunked, Date: Thu, 02 Jul 2015 09:33:02 GMT, Server: AmazonS3]

Any ideas?
Gil

**Comment by danielcompton** [comment]
Closing for now, as this uses the old jetset dependency. Please reopen if it's still an issue with the latest version.
