### ISSUE TITLE
password instead of passphrase

### ISSUE THREAD

**Issue by maxweber** [technomancy/s3-wagon-private#5]
I had trouble to use s3-wagon-private in combination with Maven, since it uses the passphrase instead of the password parameter to specify the credentials of a Maven repository. I would guess that the passphrase is only used in combination with a privateKey normally (http://maven.apache.org/ref/3.0.4/maven-settings/settings.html#class_server), so that password would be the correct parameter. However it would be nice, if the settings.xml section of the README (https://github.com/technomancy/s3-wagon-private#settingsxml) would use passphrase instead of the here not working password parameter.

Best regards

Max

**Comment by danielcompton** [comment]
@maxweber following up on this, can I understand what you're saying as:

* You expected to use a password instead of a passphrase when using this with Maven
* The documentation didn't make this clear.

At the moment, the `settings.xml` file in the README uses passphrase, I'm not sure if this is what you were asking for here?

**Comment by maxweber** [comment]
I don't remember it exactly after three years :-) But I guess it was about that the documentation was using the non-working password parameter (fixed by https://github.com/technomancy/s3-wagon-private/commit/fe7b6d43d986df041bb30c5f7e30e2f3cc0f7221). Furthermore I would say that the password parameter is the correct one, if you like to use the same terms as Maven. The Maven [documentation](https://github.com/technomancy/s3-wagon-private#settingsxml) about it says:
 `The password used in conjunction with the username to authenticate.` and `The passphrase used in conjunction with the privateKey to authenticate.`
However to stay compatible with existing configurations I would not change it.
