### ISSUE TITLE
Exception traces shown on first upload of new artifact

### ISSUE THREAD

**Issue by hugoduncan** [technomancy/s3-wagon-private#7]
The first time an artifact is deployed, the download of existing metadata obviously fails. In this case, an exception is however shown to the user, which is confusing (the deploy however succeeds). This might be just be a case of adjusting the log levels for the messages to DEBUG rather than the current WARN and SEVERE.

**Comment by danielcompton** [comment]
This shouldn't be an issue anymore with the new version as it uses the official S3 client and is much less noisy.
