### ISSUE TITLE
authentication failing under leiningen 2

### ISSUE THREAD

**Issue by mwmitchell** [technomancy/s3-wagon-private#8]
Hi,

Desperately trying to get our team upgraded to leiningen 2, so far so good but this plugin is a blocker. I've tried both :creds :gpg and :creds :env with no success.

One question I have is... the README for this project uses the :dependencies key, "private". Is this required? We actually have 2 different private s3 repos, so a single "private" would not work for us. I'm assuming this isn't the case though.

** Using :creds :env **

I have LEIN_USERNAME set to my AWS access key. I have LEIN_PASSPHRASE *and* LEIN_PASSWORD set to my AWS secret key.

I also have the recommended:

(cemerick.pomegranate.aether/register-wagon-factory!
 "s3p" #(eval '(org.springframework.aws.maven.PrivateS3Wagon.)))

... at the very bottom of my project file, and still no libs in the "lib" directory. But lots of 403 response codes from Amazon. So it seems the mechanism for s3p is working, but it's not picking up my key/secrete-key.

** Using gpg **

I installed gpg (version 2), and successfully encrypted my credentials.clj file. I can successfully decrypt as well using the gpg utility -- it asks for my passphrase, and then displays the clojure credentials map. When I set :creds to :gpg in my project file, and then run "lein deps", the process hangs and does nothing. I wonder if it's waiting for me to enter my passphrase?

With gpg, when running "lein deps" the window title switches to "pinetry curses". When I do a ctl-c (because it hangs), the output is:

^CCould not decrypt credentials from /Users/mmitchell/.lein/credentials.clj.gpg
pinentry-curses: no LC_CTYPE known - assuming UTF-8
pinentry-curses: no LC_CTYPE known - assuming UTF-8
pinentry-curses: no LC_CTYPE known - assuming UTF-8
pinentry-curses: no LC_CTYPE known - assuming UTF-8

gpg: signal Interrupt caught ... exiting

Am I doing anything wrong here? Can I provide more information to help debug this?

Thanks,

- Matt

**Comment by neverfox** [comment]
Same. Works with environment variables but not gpg.

**Comment by danielcompton** [comment]
I think this is addressed in documentation now. Closing, but happy to reopen if it's still a problem.
